name: Build docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code repository
      - name: Checkout
        uses: actions/checkout@v2
      
      # Install pnpm package manager
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.29.1
        
      # Install dependencies
      - name: Install Dependencies
        run: pnpm install

      # Run build command
      - name: Build
        run: pnpm build
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          file: ./Dockerfile
          context: ./
          push: true
          tags: hoi4tech/live-front:latest
